

server:
  error:
    include-message: always
    include-binding-errors: always

security:
  jwt:
    secret-key: "88cd2108b5347d973cf39cdf9053d7dd42704876d8c9a9bd8e2d168259d3ddf7"
    expiration-time: 1000000000


spring:
  security:
    user:
      name: TEST
      password: 12345
  datasource:
    password: 2Q3exXr226KgnH
    url: jdbc:mysql://mysql-mathis.alwaysdata.net/mathis_apijo
    username: mathis_
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true